# Generated by Django 4.2.11 on 2024-05-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fts_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_details",
                to="fts_app.user",
            ),
        ),
        migrations.AlterField(
            model_name="userrolemap",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_role_maps",
                to="fts_app.user",
            ),
        ),
    ]
