# Generated by Django 4.2.11 on 2024-05-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fts_app", "0002_alter_userdetail_user_alter_userrolemap_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondenceusermap",
            name="is_forwarded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="correspondenceusermap",
            name="is_opened",
            field=models.IntegerField(default=0),
        ),
    ]
