# Generated by Django 4.2.11 on 2024-05-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fts_app", "0003_correspondenceusermap_is_forwarded_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correspondence",
            name="department",
        ),
        migrations.RemoveField(
            model_name="correspondence",
            name="sub_department",
        ),
        migrations.RemoveField(
            model_name="userdetail",
            name="department",
        ),
        migrations.RemoveField(
            model_name="userdetail",
            name="sub_department",
        ),
    ]
