# Generated by Django 4.2.11 on 2024-05-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fts_app", "0004_remove_correspondence_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_forwarded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="is_opened",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
