# Generated by Django 4.2.11 on 2024-05-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fts_app", "0008_alter_userdetail_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondenceusermap",
            name="message",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
