# Generated by Django 4.2.11 on 2024-05-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fts_app", "0009_correspondenceusermap_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correspondenceusermap",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
