from .auth_views import *
from .user_views import *
from .messages_views import *
from .dashboard_views import * 
from .correspondences_views import *
from .ajax_views import *
from .admin import *  
from .site_views import *  
from .install_views import *
